### ISSUE TITLE
Any news on this?

### ISSUE THREAD

**Issue by agaldran** [team-approx-bayes/bayesian-sam#1]
Hello!

Very cool work, congratulations on acceptance to ICLR :) 

I was wondering if you are planning to release your code at some point in the future? It looks like you have this placeholder repo, but I cannot find any implementation here nor elsewhere...

Thanks!

**Comment by moellenh** [comment]
Hi! 

Sorry, we forgot about this! The code will be here in a couple of weeks. 

Thanks!

**Comment by agaldran** [comment]
Great thank you very much :+1:

**Comment by agaldran** [comment]
Do you mind leaving this issue opened, and closing it when you upload the code? That way I get an alert on my mail :)

**Comment by moellenh** [comment]
Yep, I'll close this issue once the code is pushed.

**Comment by lblaoke** [comment]
Also looking forward to your code. Thank you!

**Comment by DLwbm123** [comment]
Looking forward to the code. Thanks!

**Comment by moellenh** [comment]
The code is pushed now! If there's any issues or problems with it, let me know or raise an issue here.
